-- Seed the database with sample scholarship data
-- This provides realistic test data for the scholarship matching system

INSERT INTO public.scholarships (
  title,
  organization,
  amount,
  deadline,
  description,
  eligibility_criteria,
  scholarship_type,
  application_url,
  requirements,
  tags,
  target_demographics,
  matching_criteria
) VALUES 
(
  'First Generation College Student Scholarship',
  'Education Foundation',
  '$5,000',
  '2025-03-15',
  'Supporting first-generation college students who demonstrate financial need and academic potential. This scholarship recognizes the unique challenges faced by students whose parents did not attend college.',
  ARRAY['First-generation college student', 'Financial need demonstrated', 'Minimum 3.0 GPA', 'Enrolled in accredited institution'],
  'first-gen',
  'https://example.com/apply/first-gen',
  ARRAY['Personal essay (500 words)', 'Two letters of recommendation', 'Financial aid documents', 'Academic transcripts'],
  ARRAY['first-generation', 'financial-need', 'undergraduate'],
  '{"income_levels": ["low", "moderate"], "education_levels": ["undergraduate", "community-college"], "first_gen": true}',
  '{"income_level": {"low": 25, "moderate": 20}, "education_level": {"undergraduate": 15, "community-college": 15}, "gpa_range": {"3.0-3.4": 10, "3.5-4.0": 15}}'
),
(
  'STEM Diversity Scholarship',
  'Tech for All Foundation',
  '$7,500',
  '2025-04-01',
  'Empowering underrepresented students pursuing STEM degrees with financial support and mentorship opportunities. Includes access to industry networking events and internship programs.',
  ARRAY['STEM major', 'Underrepresented minority', 'Community college transfer eligible', 'Minimum 2.8 GPA'],
  'stem',
  'https://example.com/apply/stem-diversity',
  ARRAY['STEM coursework transcript', 'Research project or portfolio', 'Diversity statement', 'Faculty recommendation'],
  ARRAY['stem', 'diversity', 'technology', 'mentorship'],
  '{"majors": ["computer-science", "engineering", "mathematics", "biology", "chemistry", "physics"], "demographics": ["underrepresented"], "transfer_friendly": true}',
  '{"education_level": {"community-college": 20, "undergraduate": 15}, "gpa_range": {"2.5-2.9": 10, "3.0-3.4": 15, "3.5-4.0": 20}}'
),
(
  'English Language Learner Achievement Award',
  'Multilingual Education Alliance',
  '$3,000',
  '2025-02-28',
  'Recognizing academic excellence among students for whom English is a second language. Celebrates the resilience and determination of multilingual learners.',
  ARRAY['English as second language', 'Academic achievement', 'Community involvement', 'Leadership potential'],
  'need-based',
  'https://example.com/apply/ell-achievement',
  ARRAY['Language proficiency documentation', 'Community service record', 'Academic portfolio', 'Personal narrative'],
  ARRAY['multilingual', 'esl', 'achievement', 'community'],
  '{"language_support": ["english-second", "multilingual", "need-translation"], "community_involvement": true}',
  '{"language_support": {"english-second": 25, "multilingual": 20, "need-translation": 30}, "gpa_range": {"3.0-3.4": 15, "3.5-4.0": 20}}'
),
(
  'Neurodiversity in Education Scholarship',
  'Learning Differences Foundation',
  '$4,000',
  '2025-05-15',
  'Supporting students with learning differences who have shown resilience and determination in their educational journey. Promotes inclusive education and self-advocacy.',
  ARRAY['Documented learning differences', 'Self-advocacy demonstrated', 'Academic progress shown', 'Future goals outlined'],
  'need-based',
  'https://example.com/apply/neurodiversity',
  ARRAY['Learning difference documentation', 'Self-advocacy essay', 'Academic progress report', 'Support letter from educator'],
  ARRAY['neurodiversity', 'learning-differences', 'accessibility', 'advocacy'],
  '{"learning_needs": ["adhd", "dyslexia", "other"], "accessibility_support": true}',
  '{"learning_needs": {"adhd": 25, "dyslexia": 25, "other": 25}, "gpa_range": {"2.5-2.9": 15, "3.0-3.4": 20, "3.5-4.0": 25}}'
),
(
  'Rural Student Success Grant',
  'Rural Education Initiative',
  '$2,500',
  '2025-03-30',
  'Helping rural students access higher education opportunities and overcome geographic barriers. Includes support for transportation and technology needs.',
  ARRAY['Rural location', 'Limited educational resources', 'College-bound', 'Transportation challenges'],
  'need-based',
  'https://example.com/apply/rural-success',
  ARRAY['Rural location verification', 'Resource limitation statement', 'Transportation needs assessment', 'Educational goals essay'],
  ARRAY['rural', 'geographic-barriers', 'transportation', 'access'],
  '{"location_type": "rural", "resource_limitations": true, "transportation_needs": true}',
  '{"device_access": {"smartphone-only": 20, "smartphone-tablet": 15}, "internet_access": {"limited": 25, "mobile-only": 20}}'
),
(
  'Community College Transfer Excellence Award',
  'Transfer Student Alliance',
  '$6,000',
  '2025-04-15',
  'Recognizing outstanding community college students transferring to four-year institutions. Supports the transition with academic and financial assistance.',
  ARRAY['Community college student', 'Transferring to 4-year institution', 'Minimum 3.2 GPA', 'Leadership experience'],
  'merit-based',
  'https://example.com/apply/cc-transfer',
  ARRAY['Community college transcripts', 'Transfer acceptance letter', 'Leadership portfolio', 'Career goals statement'],
  ARRAY['transfer', 'community-college', 'leadership', 'excellence'],
  '{"education_level": ["community-college"], "transfer_student": true, "leadership": true}',
  '{"education_level": {"community-college": 30}, "gpa_range": {"3.0-3.4": 15, "3.5-4.0": 25}}'
),
(
  'Single Parent Student Support Fund',
  'Family Education Foundation',
  '$4,500',
  '2025-05-01',
  'Supporting single parents pursuing higher education while balancing family responsibilities. Includes childcare assistance and flexible scheduling support.',
  ARRAY['Single parent status', 'Enrolled in degree program', 'Financial need', 'Childcare responsibilities'],
  'need-based',
  'https://example.com/apply/single-parent',
  ARRAY['Single parent documentation', 'Childcare needs assessment', 'Financial aid forms', 'Academic plan with family considerations'],
  ARRAY['single-parent', 'family-support', 'childcare', 'flexibility'],
  '{"family_status": "single_parent", "childcare_needs": true, "flexible_scheduling": true}',
  '{"income_level": {"low": 30, "moderate": 25}, "barriers": {"childcare": 20, "time_management": 15}}'
),
(
  'International Student Integration Scholarship',
  'Global Education Network',
  '$5,500',
  '2025-03-01',
  'Supporting international students in their academic and cultural integration journey. Includes mentorship programs and cultural exchange opportunities.',
  ARRAY['International student status', 'F-1 or J-1 visa', 'Academic good standing', 'Cultural integration goals'],
  'international',
  'https://example.com/apply/international',
  ARRAY['Visa documentation', 'Academic transcripts', 'Cultural integration essay', 'Mentor program participation agreement'],
  ARRAY['international', 'cultural-integration', 'mentorship', 'global'],
  '{"visa_status": ["F-1", "J-1"], "cultural_support": true, "mentorship": true}',
  '{"language_support": {"english-second": 20, "need-translation": 25}, "barriers": {"cultural_adjustment": 20, "language": 15}}'
);
